In [1]:
import numpy as np
import pandas
from sklearn.tree import DecisionTreeClassifier

In [2]:
data = pandas.read_csv('titanic.csv', index_col='PassengerId')
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [3]:
train_data = np.delete(data.as_matrix(), [2, 5, 6, 7, 9, 10], axis=1)  # Remove unnecessary attributes

In [4]:
for i, item in enumerate(train_data):
    train_data[i][2] = int(item[2] == 'male')  # Convert string male/female attributes to numeric

In [5]:
train_data = np.array(train_data, dtype=np.float32)
train_data = train_data[~np.isnan(train_data).any(1)]  # Remove items that contain NaN attributes

In [6]:
train_labels = np.array([])
for item in train_data:
    train_labels = np.append(train_labels, item[0])  # Prepare training labels
    
train_data = np.delete(train_data, 0, axis=1)

In [7]:
print train_data

[[  3.           1.          22.           7.25      ]
 [  1.           0.          38.          71.28330231]
 [  3.           0.          26.           7.92500019]
 ..., 
 [  1.           0.          19.          30.        ]
 [  1.           1.          26.          30.        ]
 [  3.           1.          32.           7.75      ]]


In [9]:
classifier = DecisionTreeClassifier(random_state=241)
classifier.fit(train_data, train_labels)  # Train the decision tree classifier

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=241, splitter='best')

In [10]:
print classifier.feature_importances_

[ 0.14000522  0.30051221  0.2560461   0.30343647]
