In [53]:
import numpy as np
import pandas
from sklearn.tree import DecisionTreeClassifier

In [54]:
data = pandas.read_csv('titanic.csv', index_col='PassengerId')
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [55]:
train_data = np.delete(data.as_matrix(), [2, 5, 6, 7, 9, 10], axis=1)  # Remove unnecessary attributes

In [56]:
for i, item in enumerate(train_data):
    train_data[i][2] = int(item[2] == 'male')  # Convert string male/female attributes to numeric

In [57]:
train_data = np.array(train_data, dtype=np.float32)
train_data = train_data[~np.isnan(train_data).any(1)]  # Remove items that contain NaN attributes

In [58]:
train_labels = np.array([])
for item in train_data:
    train_labels = np.append(train_labels, item[0])  # Prepare training labels
    
train_data = np.delete(train_data, 0, axis=1)

In [59]:
print train_data

[[  3.           1.          22.           7.25      ]
 [  1.           0.          38.          71.28330231]
 [  3.           0.          26.           7.92500019]
 ..., 
 [  1.           0.          19.          30.        ]
 [  1.           1.          26.          30.        ]
 [  3.           1.          32.           7.75      ]]


In [60]:
classifier = DecisionTreeClassifier(random_state=241)
classifier.fit(train_data, train_labels)  # Train the decision tree classifier

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=241, splitter='best')

In [61]:
print classifier.feature_importances_

[ 0.14000522  0.30051221  0.2560461   0.30343647]


In [62]:
test = pandas.read_csv('test.csv', index_col='PassengerId')
test.head()

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

              Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
PassengerId                                                       
892          34.5      0      0   330911   7.8292   NaN        Q  
893          47.0      1      0   363272   7.0000   NaN        S  
894          62.0      0      0   240276   9.6875   NaN        Q  
895          27.0      0      0   315154   8.6625   NaN        S  
896          22.0      1      1  3101298  12.2875   NaN        S

In [63]:
test_data = np.delete(test.as_matrix(), [1, 4, 5, 6, 8, 9], axis=1)
test_data

array([[3, 'male', 34.5, 7.8292],
       [3, 'female', 47.0, 7.0],
       [2, 'male', 62.0, 9.6875],
       ..., 
       [3, 'male', 38.5, 7.25],
       [3, 'male', nan, 8.05],
       [3, 'male', nan, 22.3583]], dtype=object)

In [64]:
for i, item in enumerate(test_data):
    test_data[i][1] = int(item[1] == 'male')

In [65]:
test_data = np.array(test_data, dtype=np.float32)

In [66]:
for i, item in enumerate(test_data):
    if np.isnan(item[2]):
        test_data[i][2] = 28
    if np.isnan(item[0]):
        test_data[i][0] = 2
    if np.isnan(item[3]):
        test_data[i][3] = 10

In [67]:
pr = classifier.predict(test_data)

In [69]:
test['Survived'] = pr

In [72]:
test.to_csv('res.csv')